version: '3'

services:
  db:
    container_name: edusys_mysql
    image: mysql:debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 33063:3306
